/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Complaint = IDL.Record({
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'status' : IDL.Text,
  'complaintId' : IDL.Text,
  'verificationPhotoUrl' : IDL.Text,
  'complaintType' : IDL.Text,
  'userId' : UserId,
  'aiAnalysisResult' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'assignedAuthority' : IDL.Text,
  'updatedAt' : Timestamp,
  'locationAddress' : IDL.Text,
  'aiSeverity' : IDL.Text,
  'citizenVerification' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ChatSession = IDL.Record({
  'messages' : IDL.Vec(ChatMessage),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'sessionId' : IDL.Nat,
});
export const Contractor = IDL.Record({
  'status' : IDL.Text,
  'timelineScore' : IDL.Float64,
  'overallScore' : IDL.Float64,
  'name' : IDL.Text,
  'contractorId' : IDL.Nat,
  'qualityScore' : IDL.Float64,
  'state' : IDL.Text,
  'complaintScore' : IDL.Float64,
  'projectsCompleted' : IDL.Nat,
});
export const DriverSafetyScore = IDL.Record({
  'assessedAt' : Timestamp,
  'userId' : UserId,
  'answers' : IDL.Text,
  'score' : IDL.Nat,
});
export const EmergencyProfile = IDL.Record({
  'principal' : UserId,
  'emergencyContact1Phone' : IDL.Text,
  'insuranceProvider' : IDL.Text,
  'additionalNotes' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'emergencyContact2Name' : IDL.Text,
  'emergencyContact2Phone' : IDL.Text,
  'updatedAt' : Timestamp,
  'bloodGroup' : IDL.Text,
  'emergencyContact1Name' : IDL.Text,
  'allergies' : IDL.Text,
  'policyNumber' : IDL.Text,
});
export const LegalUpdate = IDL.Record({
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'publishedAt' : Timestamp,
  'sourceUrl' : IDL.Text,
  'updateId' : IDL.Nat,
  'summary' : IDL.Text,
  'state' : IDL.Text,
});
export const RoadRating = IDL.Record({
  'id' : IDL.Text,
  'review' : IDL.Text,
  'roadName' : IDL.Text,
  'submitter' : IDL.Text,
  'city' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const RescueService = IDL.Record({
  'serviceType' : IDL.Text,
  'isAvailable247' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'serviceId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const RoadProject = IDL.Record({
  'utilizedBudget' : IDL.Float64,
  'releasedBudget' : IDL.Float64,
  'name' : IDL.Text,
  'lastUpdated' : Timestamp,
  'state' : IDL.Text,
  'completionPercent' : IDL.Float64,
  'projectId' : IDL.Nat,
  'totalBudget' : IDL.Float64,
  'location' : IDL.Text,
  'contractorName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'language' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});
export const ComplaintInput = IDL.Record({
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'complaintType' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'locationAddress' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : RoadRating, 'err' : IDL.Text });
export const EmergencyProfileInput = IDL.Record({
  'emergencyContact1Phone' : IDL.Text,
  'insuranceProvider' : IDL.Text,
  'additionalNotes' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'emergencyContact2Name' : IDL.Text,
  'emergencyContact2Phone' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'emergencyContact1Name' : IDL.Text,
  'allergies' : IDL.Text,
  'policyNumber' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'language' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMessageToSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatSession' : IDL.Func([], [IDL.Nat], []),
  'deleteChatSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatSession' : IDL.Func([IDL.Nat], [IDL.Opt(ChatSession)], []),
  'getChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], []),
  'getCityRoads' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getComplaint' : IDL.Func([IDL.Text], [IDL.Opt(Complaint)], ['query']),
  'getContractors' : IDL.Func([IDL.Text], [IDL.Vec(Contractor)], ['query']),
  'getDriverSafetyScore' : IDL.Func([], [IDL.Opt(DriverSafetyScore)], []),
  'getEmergencyProfile' : IDL.Func([], [IDL.Opt(EmergencyProfile)], []),
  'getLegalUpdates' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(LegalUpdate)],
      ['query'],
    ),
  'getRatingsForRoad' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(RoadRating)],
      ['query'],
    ),
  'getRescueServices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(RescueService)],
      ['query'],
    ),
  'getRoadProjects' : IDL.Func([IDL.Text], [IDL.Vec(RoadProject)], ['query']),
  'getUserComplaints' : IDL.Func([], [IDL.Vec(Complaint)], []),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveDriverSafetyScore' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'submitComplaint' : IDL.Func([ComplaintInput], [IDL.Text], []),
  'submitRoadRating' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'updateComplaintVerification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'upsertEmergencyProfile' : IDL.Func([EmergencyProfileInput], [IDL.Bool], []),
  'upsertUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Complaint = IDL.Record({
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'status' : IDL.Text,
    'complaintId' : IDL.Text,
    'verificationPhotoUrl' : IDL.Text,
    'complaintType' : IDL.Text,
    'userId' : UserId,
    'aiAnalysisResult' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'assignedAuthority' : IDL.Text,
    'updatedAt' : Timestamp,
    'locationAddress' : IDL.Text,
    'aiSeverity' : IDL.Text,
    'citizenVerification' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ChatSession = IDL.Record({
    'messages' : IDL.Vec(ChatMessage),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'sessionId' : IDL.Nat,
  });
  const Contractor = IDL.Record({
    'status' : IDL.Text,
    'timelineScore' : IDL.Float64,
    'overallScore' : IDL.Float64,
    'name' : IDL.Text,
    'contractorId' : IDL.Nat,
    'qualityScore' : IDL.Float64,
    'state' : IDL.Text,
    'complaintScore' : IDL.Float64,
    'projectsCompleted' : IDL.Nat,
  });
  const DriverSafetyScore = IDL.Record({
    'assessedAt' : Timestamp,
    'userId' : UserId,
    'answers' : IDL.Text,
    'score' : IDL.Nat,
  });
  const EmergencyProfile = IDL.Record({
    'principal' : UserId,
    'emergencyContact1Phone' : IDL.Text,
    'insuranceProvider' : IDL.Text,
    'additionalNotes' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'emergencyContact2Name' : IDL.Text,
    'emergencyContact2Phone' : IDL.Text,
    'updatedAt' : Timestamp,
    'bloodGroup' : IDL.Text,
    'emergencyContact1Name' : IDL.Text,
    'allergies' : IDL.Text,
    'policyNumber' : IDL.Text,
  });
  const LegalUpdate = IDL.Record({
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'publishedAt' : Timestamp,
    'sourceUrl' : IDL.Text,
    'updateId' : IDL.Nat,
    'summary' : IDL.Text,
    'state' : IDL.Text,
  });
  const RoadRating = IDL.Record({
    'id' : IDL.Text,
    'review' : IDL.Text,
    'roadName' : IDL.Text,
    'submitter' : IDL.Text,
    'city' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const RescueService = IDL.Record({
    'serviceType' : IDL.Text,
    'isAvailable247' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'serviceId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const RoadProject = IDL.Record({
    'utilizedBudget' : IDL.Float64,
    'releasedBudget' : IDL.Float64,
    'name' : IDL.Text,
    'lastUpdated' : Timestamp,
    'state' : IDL.Text,
    'completionPercent' : IDL.Float64,
    'projectId' : IDL.Nat,
    'totalBudget' : IDL.Float64,
    'location' : IDL.Text,
    'contractorName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'language' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ComplaintInput = IDL.Record({
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'complaintType' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'locationAddress' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : RoadRating, 'err' : IDL.Text });
  const EmergencyProfileInput = IDL.Record({
    'emergencyContact1Phone' : IDL.Text,
    'insuranceProvider' : IDL.Text,
    'additionalNotes' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'emergencyContact2Name' : IDL.Text,
    'emergencyContact2Phone' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'emergencyContact1Name' : IDL.Text,
    'allergies' : IDL.Text,
    'policyNumber' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'language' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMessageToSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatSession' : IDL.Func([], [IDL.Nat], []),
    'deleteChatSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatSession' : IDL.Func([IDL.Nat], [IDL.Opt(ChatSession)], []),
    'getChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], []),
    'getCityRoads' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getComplaint' : IDL.Func([IDL.Text], [IDL.Opt(Complaint)], ['query']),
    'getContractors' : IDL.Func([IDL.Text], [IDL.Vec(Contractor)], ['query']),
    'getDriverSafetyScore' : IDL.Func([], [IDL.Opt(DriverSafetyScore)], []),
    'getEmergencyProfile' : IDL.Func([], [IDL.Opt(EmergencyProfile)], []),
    'getLegalUpdates' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(LegalUpdate)],
        ['query'],
      ),
    'getRatingsForRoad' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(RoadRating)],
        ['query'],
      ),
    'getRescueServices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(RescueService)],
        ['query'],
      ),
    'getRoadProjects' : IDL.Func([IDL.Text], [IDL.Vec(RoadProject)], ['query']),
    'getUserComplaints' : IDL.Func([], [IDL.Vec(Complaint)], []),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveDriverSafetyScore' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'submitComplaint' : IDL.Func([ComplaintInput], [IDL.Text], []),
    'submitRoadRating' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'updateComplaintVerification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'upsertEmergencyProfile' : IDL.Func(
        [EmergencyProfileInput],
        [IDL.Bool],
        [],
      ),
    'upsertUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };