/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : string,
  'role' : string,
  'timestamp' : Timestamp,
}
export interface ChatSession {
  'messages' : Array<ChatMessage>,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'sessionId' : bigint,
}
export interface Complaint {
  'locationLat' : number,
  'locationLng' : number,
  'status' : string,
  'complaintId' : string,
  'verificationPhotoUrl' : string,
  'complaintType' : string,
  'userId' : UserId,
  'aiAnalysisResult' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'photoUrl' : string,
  'assignedAuthority' : string,
  'updatedAt' : Timestamp,
  'locationAddress' : string,
  'aiSeverity' : string,
  'citizenVerification' : string,
}
export interface ComplaintInput {
  'locationLat' : number,
  'locationLng' : number,
  'complaintType' : string,
  'description' : string,
  'photoUrl' : string,
  'locationAddress' : string,
}
export interface Contractor {
  'status' : string,
  'timelineScore' : number,
  'overallScore' : number,
  'name' : string,
  'contractorId' : bigint,
  'qualityScore' : number,
  'state' : string,
  'complaintScore' : number,
  'projectsCompleted' : bigint,
}
export interface DriverSafetyScore {
  'assessedAt' : Timestamp,
  'userId' : UserId,
  'answers' : string,
  'score' : bigint,
}
export interface EmergencyProfile {
  'principal' : UserId,
  'emergencyContact1Phone' : string,
  'insuranceProvider' : string,
  'additionalNotes' : string,
  'medicalConditions' : string,
  'emergencyContact2Name' : string,
  'emergencyContact2Phone' : string,
  'updatedAt' : Timestamp,
  'bloodGroup' : string,
  'emergencyContact1Name' : string,
  'allergies' : string,
  'policyNumber' : string,
}
export interface EmergencyProfileInput {
  'emergencyContact1Phone' : string,
  'insuranceProvider' : string,
  'additionalNotes' : string,
  'medicalConditions' : string,
  'emergencyContact2Name' : string,
  'emergencyContact2Phone' : string,
  'bloodGroup' : string,
  'emergencyContact1Name' : string,
  'allergies' : string,
  'policyNumber' : string,
}
export interface LegalUpdate {
  'title' : string,
  'topic' : string,
  'publishedAt' : Timestamp,
  'sourceUrl' : string,
  'updateId' : bigint,
  'summary' : string,
  'state' : string,
}
export interface RescueService {
  'serviceType' : string,
  'isAvailable247' : boolean,
  'city' : string,
  'name' : string,
  'state' : string,
  'address' : string,
  'rating' : number,
  'serviceId' : bigint,
  'phone' : string,
}
export type Result = { 'ok' : RoadRating } |
  { 'err' : string };
export interface RoadProject {
  'utilizedBudget' : number,
  'releasedBudget' : number,
  'name' : string,
  'lastUpdated' : Timestamp,
  'state' : string,
  'completionPercent' : number,
  'projectId' : bigint,
  'totalBudget' : number,
  'location' : string,
  'contractorName' : string,
}
export interface RoadRating {
  'id' : string,
  'review' : string,
  'roadName' : string,
  'submitter' : string,
  'city' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'language' : string,
  'updatedAt' : Timestamp,
  'state' : string,
  'phone' : string,
}
export interface UserProfileInput {
  'city' : string,
  'name' : string,
  'language' : string,
  'state' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMessageToSession' : ActorMethod<[bigint, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatSession' : ActorMethod<[], bigint>,
  'deleteChatSession' : ActorMethod<[bigint], boolean>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatSession' : ActorMethod<[bigint], [] | [ChatSession]>,
  'getChatSessions' : ActorMethod<[], Array<ChatSession>>,
  'getCityRoads' : ActorMethod<[string], Array<string>>,
  'getComplaint' : ActorMethod<[string], [] | [Complaint]>,
  'getContractors' : ActorMethod<[string], Array<Contractor>>,
  'getDriverSafetyScore' : ActorMethod<[], [] | [DriverSafetyScore]>,
  'getEmergencyProfile' : ActorMethod<[], [] | [EmergencyProfile]>,
  'getLegalUpdates' : ActorMethod<[string, string], Array<LegalUpdate>>,
  'getRatingsForRoad' : ActorMethod<[string, string], Array<RoadRating>>,
  'getRescueServices' : ActorMethod<[string, string], Array<RescueService>>,
  'getRoadProjects' : ActorMethod<[string], Array<RoadProject>>,
  'getUserComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveDriverSafetyScore' : ActorMethod<[bigint, string], boolean>,
  'submitComplaint' : ActorMethod<[ComplaintInput], string>,
  'submitRoadRating' : ActorMethod<[string, string, bigint, string], Result>,
  'updateComplaintVerification' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'upsertEmergencyProfile' : ActorMethod<[EmergencyProfileInput], boolean>,
  'upsertUserProfile' : ActorMethod<[UserProfileInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];