/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    principal: UserId;
    city: string;
    name: string;
    createdAt: Timestamp;
    language: string;
    updatedAt: Timestamp;
    state: string;
    phone: string;
}
export interface ComplaintInput {
    locationLat: number;
    locationLng: number;
    complaintType: string;
    description: string;
    photoUrl: string;
    locationAddress: string;
}
export type Timestamp = bigint;
export interface EmergencyProfile {
    principal: UserId;
    emergencyContact1Phone: string;
    insuranceProvider: string;
    additionalNotes: string;
    medicalConditions: string;
    emergencyContact2Name: string;
    emergencyContact2Phone: string;
    updatedAt: Timestamp;
    bloodGroup: string;
    emergencyContact1Name: string;
    allergies: string;
    policyNumber: string;
}
export interface DriverSafetyScore {
    assessedAt: Timestamp;
    userId: UserId;
    answers: string;
    score: bigint;
}
export interface RoadProject {
    utilizedBudget: number;
    releasedBudget: number;
    name: string;
    lastUpdated: Timestamp;
    state: string;
    completionPercent: number;
    projectId: bigint;
    totalBudget: number;
    location: string;
    contractorName: string;
}
export interface ChatSession {
    messages: Array<ChatMessage>;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    sessionId: bigint;
}
export interface RoadRating {
    id: string;
    review: string;
    roadName: string;
    submitter: string;
    city: string;
    timestamp: bigint;
    rating: bigint;
}
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: RoadRating;
} | {
    __kind__: "err";
    err: string;
};
export interface LegalUpdate {
    title: string;
    topic: string;
    publishedAt: Timestamp;
    sourceUrl: string;
    updateId: bigint;
    summary: string;
    state: string;
}
export interface Contractor {
    status: string;
    timelineScore: number;
    overallScore: number;
    name: string;
    contractorId: bigint;
    qualityScore: number;
    state: string;
    complaintScore: number;
    projectsCompleted: bigint;
}
export interface Complaint {
    locationLat: number;
    locationLng: number;
    status: string;
    complaintId: string;
    verificationPhotoUrl: string;
    complaintType: string;
    userId: UserId;
    aiAnalysisResult: string;
    createdAt: Timestamp;
    description: string;
    photoUrl: string;
    assignedAuthority: string;
    updatedAt: Timestamp;
    locationAddress: string;
    aiSeverity: string;
    citizenVerification: string;
}
export interface ChatMessage {
    content: string;
    role: string;
    timestamp: Timestamp;
}
export interface UserProfileInput {
    city: string;
    name: string;
    language: string;
    state: string;
    phone: string;
}
export interface RescueService {
    serviceType: string;
    isAvailable247: boolean;
    city: string;
    name: string;
    state: string;
    address: string;
    rating: number;
    serviceId: bigint;
    phone: string;
}
export interface EmergencyProfileInput {
    emergencyContact1Phone: string;
    insuranceProvider: string;
    additionalNotes: string;
    medicalConditions: string;
    emergencyContact2Name: string;
    emergencyContact2Phone: string;
    bloodGroup: string;
    emergencyContact1Name: string;
    allergies: string;
    policyNumber: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addMessageToSession(sessionId: bigint, role: string, content: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChatSession(): Promise<bigint>;
    deleteChatSession(sessionId: bigint): Promise<boolean>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getCallerUserRole(): Promise<UserRole>;
    getChatSession(sessionId: bigint): Promise<ChatSession | null>;
    getChatSessions(): Promise<Array<ChatSession>>;
    getCityRoads(city: string): Promise<Array<string>>;
    getComplaint(complaintId: string): Promise<Complaint | null>;
    getContractors(state: string): Promise<Array<Contractor>>;
    getDriverSafetyScore(): Promise<DriverSafetyScore | null>;
    getEmergencyProfile(): Promise<EmergencyProfile | null>;
    getLegalUpdates(state: string, topic: string): Promise<Array<LegalUpdate>>;
    getRatingsForRoad(city: string, roadName: string): Promise<Array<RoadRating>>;
    getRescueServices(serviceType: string, city: string): Promise<Array<RescueService>>;
    getRoadProjects(state: string): Promise<Array<RoadProject>>;
    getUserComplaints(): Promise<Array<Complaint>>;
    getUserProfile(): Promise<UserProfile | null>;
    healthCheck(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    saveDriverSafetyScore(score: bigint, answers: string): Promise<boolean>;
    submitComplaint(input: ComplaintInput): Promise<string>;
    submitRoadRating(city: string, roadName: string, rating: bigint, review: string): Promise<Result>;
    updateComplaintVerification(complaintId: string, verification: string, photoUrl: string): Promise<boolean>;
    upsertEmergencyProfile(input: EmergencyProfileInput): Promise<boolean>;
    upsertUserProfile(input: UserProfileInput): Promise<boolean>;
}
import type { ChatSession as _ChatSession, Complaint as _Complaint, DriverSafetyScore as _DriverSafetyScore, EmergencyProfile as _EmergencyProfile, Result as _Result, RoadRating as _RoadRating, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addMessageToSession(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessageToSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessageToSession(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChatSession(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatSession();
            return result;
        }
    }
    async deleteChatSession(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatSession(arg0);
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatSession(arg0: bigint): Promise<ChatSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSession(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSession(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatSessions(): Promise<Array<ChatSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSessions();
            return result;
        }
    }
    async getCityRoads(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityRoads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityRoads(arg0);
            return result;
        }
    }
    async getComplaint(arg0: string): Promise<Complaint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractors(arg0: string): Promise<Array<Contractor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractors(arg0);
            return result;
        }
    }
    async getDriverSafetyScore(): Promise<DriverSafetyScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverSafetyScore();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverSafetyScore();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyProfile(): Promise<EmergencyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalUpdates(arg0: string, arg1: string): Promise<Array<LegalUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalUpdates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalUpdates(arg0, arg1);
            return result;
        }
    }
    async getRatingsForRoad(arg0: string, arg1: string): Promise<Array<RoadRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForRoad(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForRoad(arg0, arg1);
            return result;
        }
    }
    async getRescueServices(arg0: string, arg1: string): Promise<Array<RescueService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRescueServices(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRescueServices(arg0, arg1);
            return result;
        }
    }
    async getRoadProjects(arg0: string): Promise<Array<RoadProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoadProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoadProjects(arg0);
            return result;
        }
    }
    async getUserComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserComplaints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserComplaints();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveDriverSafetyScore(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDriverSafetyScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDriverSafetyScore(arg0, arg1);
            return result;
        }
    }
    async submitComplaint(arg0: ComplaintInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(arg0);
            return result;
        }
    }
    async submitRoadRating(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRoadRating(arg0, arg1, arg2, arg3);
                return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRoadRating(arg0, arg1, arg2, arg3);
            return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateComplaintVerification(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintVerification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintVerification(arg0, arg1, arg2);
            return result;
        }
    }
    async upsertEmergencyProfile(arg0: EmergencyProfileInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertEmergencyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertEmergencyProfile(arg0);
            return result;
        }
    }
    async upsertUserProfile(arg0: UserProfileInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_Result_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatSession]): ChatSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Complaint]): Complaint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverSafetyScore]): DriverSafetyScore | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmergencyProfile]): EmergencyProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RoadRating;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RoadRating;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
